printing-server:
    directory: "/etc/icpc-printer/queue"
    users: "/etc/icpc-printer/users.csv"
    tokens: "/etc/icpc-printer/tokens.csv"

server:
    port: 443
    ssl:
        key-store: "/home/ejudge/keystore.p12"
        key-store-password: "ejejej"
        key-store-type: "PKCS12"
        key-alias: "tomcat"
